-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');

-- CreateTable
-- Migration script for Prisma schema

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE,
    fullname VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS m_ikan (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(255) UNIQUE NOT NULL,
    gambar_url VARCHAR(255),
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS m_kondisi_ikan (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(255) UNIQUE NOT NULL,
    deskripsi TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS m_kapal (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS m_pelabuhan (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(255) UNIQUE NOT NULL,
    lokasi_lat FLOAT,
    lokasi_lng FLOAT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS m_cold_storage (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tr_tangkapan (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    kapal_id INT NOT NULL,
    pelabuhan_id INT NOT NULL,
    tanggal_penangkapan TIMESTAMP WITH TIME ZONE NOT NULL,
    waktu_penangkapan TIMESTAMP WITH TIME ZONE NOT NULL,
    catatan TEXT,
    lokasi_lat FLOAT,
    lokasi_lng FLOAT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_kapal FOREIGN KEY(kapal_id) REFERENCES m_kapal(id),
    CONSTRAINT fk_pelabuhan FOREIGN KEY(pelabuhan_id) REFERENCES m_pelabuhan(id)
);

CREATE TABLE IF NOT EXISTS tr_tangkapan_detail (
    id SERIAL PRIMARY KEY,
    tangkapan_id INT NOT NULL,
    ikan_id INT NOT NULL,
    id_qr BIGINT UNIQUE,
    total_berat_kg FLOAT NOT NULL,
    kondisi_ikan_id INT NOT NULL,
    tanggal_masuk_coldstorage TIMESTAMP WITH TIME ZONE,
    cold_storage_id INT,
    posisi_penyimpanan_coldstorage VARCHAR(255),
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT fk_tangkapan FOREIGN KEY(tangkapan_id) REFERENCES tr_tangkapan(id),
    CONSTRAINT fk_ikan FOREIGN KEY(ikan_id) REFERENCES m_ikan(id),
    CONSTRAINT fk_kondisi_ikan FOREIGN KEY(kondisi_ikan_id) REFERENCES m_kondisi_ikan(id),
    CONSTRAINT fk_cold_storage FOREIGN KEY(cold_storage_id) REFERENCES m_cold_storage(id)
);

CREATE TABLE IF NOT EXISTS tr_deteksi_ikan (
    id SERIAL PRIMARY KEY,
    tangkapan_detail_id INT NOT NULL,
    ikan_id INT NOT NULL,
    akurasi FLOAT NOT NULL,
    dipilih BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT fk_tangkapan_detail FOREIGN KEY(tangkapan_detail_id) REFERENCES tr_tangkapan_detail(id),
    CONSTRAINT fk_ikan_deteksi FOREIGN KEY(ikan_id) REFERENCES m_ikan(id)
);

CREATE TABLE IF NOT EXISTS tr_histori_produksi (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    ikan_id INT NOT NULL,
    tanggal DATE NOT NULL,
    total_berat_kg FLOAT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT fk_user_produksi FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_ikan_produksi FOREIGN KEY(ikan_id) REFERENCES m_ikan(id),
    UNIQUE(user_id, ikan_id, tanggal)
);

CREATE TABLE IF NOT EXISTS tr_tangkapan_qr (
    id_qr BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    original_name VARCHAR(255) NOT NULL,
    s3_key VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    file_size INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);


-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");
