name: CI/CD for NestJS & Prisma

on:
  push:
    branches:
      - main   # Menjalankan action saat ada perubahan pada branch 'main'
  pull_request:
    branches:
      - main   # Menjalankan action pada pull request ke 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Mengambil kode dari repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Gunakan versi Node.js yang diinginkan

      - name: Install dependencies
        run: |
          npm ci  # Menginstal dependencies dari package-lock.json

      - name: Install Prisma
        run: npm install prisma @prisma/client  # Menginstal Prisma

      - name: Run Prisma Generate
        run: npx prisma generate  # Menghasilkan Prisma Client

      - name: Run Tests
        run: npm run test -- --ci --coverage  # Menjalankan unit test dengan Jest

      - name: Build the application
        run: npm run build  # Membangun aplikasi NestJS

      - name: Deploy to server (auto deployment using SSH)
        if: github.ref == 'refs/heads/main'  # Memastikan hanya di branch 'main'
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip "
            cd /path/to/your/app && git pull origin main && npm ci && npm run build && pm2 restart all
          "  # SSH ke server dan menjalankan perintah update dan restart aplikasi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH key untuk autentikasi
          SERVER_IP: ${{ secrets.SERVER_IP }}  # IP server

